In [18]:
import pandas as pd

# **Working with JSON**

# get from local machine

In [19]:
pd.read_json('recipes.json')

,id,url,image,name,description,author,rattings,ingredients,steps,nutrients,times,serves,difficult,vote_count,subcategory,dish_type,maincategory
0,7bac6ec3-fb66-4543-80f5-4b692de7a811,https://www.bbcgoodfood.com/recipes/smoked-sal...,https://images.immediate.co.uk/production/vola...,"Smoked salmon, quinoa & dill lunch pot",This easy packed lunch is as delicious as it i...,Chelsie Collins,4,"[2 tbsp half-fat soured cream, 2 tbsp lemon ju...","[First, make the dressing. Mix the soured crea...","{'kcal': '254', 'fat': '7g', 'saturates': '2g'...","{'Preparation': '15 mins', 'Cooking': 'No Time'}",2,Easy,10,Lunch recipes,Quick lunch recipes,recipes
1,25009e0a-0e60-4169-9f76-f464225549a9,https://www.bbcgoodfood.com/recipes/air-fryer-...,https://images.immediate.co.uk/production/vola...,Air fryer chicken breasts,Use an air fryer to create this tempting dish ...,Samuel Goldsmith,5,"[4 chicken breasts, ½ tbsp rapeseed oil, 1 ts...",[Coat the chicken in the oil and set aside. In...,{},"{'Preparation': '5 mins', 'Cooking': '18 mins ...",4,Easy,10,Lunch recipes,Quick lunch recipes,recipes
2,63ff8ff6-2871-4e92-96fd-39964c423a39,https://www.bbcgoodfood.com/recipes/panuozzo-s...,https://images.immediate.co.uk/production/vola...,Panuozzo sandwich,Make your own baguettes and pesto to make thes...,Paul Ainsworth,5,"[300g strong white bread flour, plus extra for...","[Put the flour in a large bowl, then stir in t...",{},"{'Preparation': '20 mins', 'Cooking': '12 mins'}",4,Easy,4,Lunch recipes,Quick lunch recipes,recipes
3,9e62330f-5ea0-4c2a-b0c8-edf386b63fb7,https://www.bbcgoodfood.com/recipes/bulgur-qui...,https://images.immediate.co.uk/production/vola...,Bulgur & quinoa lunch bowls,These meal prep grain bowls use one base and t...,Sara Buenfeld,5,"[1 large onion, very finely chopped, 150g bulg...","[Tip the onion and bulgur mix into a pan, pour...","{'kcal': '369', 'fat': '20g', 'saturates': '4g...","{'Preparation': '5 mins', 'Cooking': '15 mins'}",4,Easy,18,Lunch recipes,Quick lunch recipes,recipes
4,c095701c-a11e-4f47-90a0-a3ea20f7c752,https://www.bbcgoodfood.com/recipes/falafel-bu...,https://images.immediate.co.uk/production/vola...,Falafel burgers,A healthy burger that's filling too. These are...,Good Food team,4,"[400g can chickpeas, rinsed and drained, 1 sm...",[Drain the chickpeas and pat dry with kitchen ...,"{'kcal': '161', 'fat': '8g', 'saturates': '1g'...","{'Preparation': '10 mins', 'Cooking': '6 mins'}",4,Easy,710,Lunch recipes,Quick lunch recipes,recipes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017,5238754f-2864-475b-9568-c7b4c473abcf,https://www.bbcgoodfood.com/recipes/slow-cooke...,https://images.immediate.co.uk/production/vola...,Slow cooker Turkish breakfast eggs,Spice up your baked eggs and get two of your f...,Good Food team,4,"[1 tbsp olive oil, 2 onions, finely sliced, 1 ...",[Oil the inside of a small slow cooker and hea...,"{'kcal': '165', 'fat': '8g', 'saturates': '2g'...","{'Preparation': '15 mins', 'Cooking': '5 hrs -...",4,Easy,11,Vegetarian,Vegetarian slow cooker,recipes
1018,c83a5362-cba4-4f59-a398-1058bdcf6300,https://www.bbcgoodfood.com/recipes/spiced-car...,https://images.immediate.co.uk/production/vola...,Spiced carrot & lentil soup,"A delicious, spicy blend packed full of iron a...",Jane Hornby,5,"[2 tsp cumin seeds, pinch chilli flakes, 2 tbs...",[Heat a large saucepan and dry-fry 2 tsp cumin...,"{'kcal': '238', 'fat': '7g', 'saturates': '1g'...","{'Preparation': '10 mins', 'Cooking': '15 mins'}",4,Easy,1280,Vegetarian,Vegetarian slow cooker,recipes
1019,b63ee847-860b-4873-a35c-222c42feddee,https://www.bbcgoodfood.com/recipes/slow-cooke...,https://images.immediate.co.uk/production/vola...,Slow-cooked marrow with fennel & tomato,Try this vegetarian stew with crusty sourdough...,Rosie Birkett,4,"[1 young marrow (about 1kg), 4 tbsp olive oil,...","[Halve, deseed and chop the marrow into chunks...",{},"{'Preparation': '30 mins', 'Cooking': '1 hr'}",4,Easy,25,Vegetarian,Vegetarian slow cooker,recipes
1020,4d1f3f8e-7328-47af-ae94-5afe00850552,https://www.bbcgoodfood.com/recipes/5-day-tagine,https://images.immediate.co.uk/production/vola...,5-a-day tagine,Get your day's vegetable quota all in one go. ...,Good Food team,4,"[4 carrots, cut into chunks, 4 small parsnips,...",[Heat oven to 200C/fan 180C/gas 6. Scatter the...,"{'kcal': '272', 'fat': '8g', 'saturates': '1g'...","{'Preparation': '10 mins', 'Cooking': '35 mins'}",4,Easy,219,Vegetarian,Vegetarian slow cooker,recipes
1021,7f93d0f9-0beb-4781-8ea1-6f60bc4e2272,https://www.bbcgoodfood.com/recipes/slow-cooke...,https://images.immediate.co.uk/production/vola...,Slow cooker clotted cream fudge,Dig out your slow cooker to make some moreish ...,Anna Glover,4,"[300g golden caster sugar, 100g golden syrup, ...","[Put the caster sugar, golden syrup, clotted c...",{},"{'Preparation': '15 mins', 'Cooking': '5 hrs'}",16,Easy,4,Vegetarian,Vegetarian slow cooker,recipes

# get from url

In [20]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.0385
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.6740
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.8620
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,3.8600
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.1700
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.1930
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-07,1783382401,0.2820

# **Working with SQL**

In [21]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in /usr/local/lib/python3.12/dist-packages (2.2.9)

In [22]:
import mysql.connector

In [27]:
conn = mysql.connector.connect(host='local host',user='root',password='',database='world')  # if work remote- host = uska ip address

InterfaceError: 2003: Can't connect to MySQL server on 'local host:3306' (-2 Name or service not known)

In [28]:
pd.read_sql_query("SELECT * FROM city",conn)

NameError: name 'conn' is not defined

# Read more about sql querry

In [30]:
url = 'https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html#pandas.read_sql_query'
print(url)

https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html#pandas.read_sql_query